version: "3.5"
services:
  web:
    image: manuelarias/pets-web:1.2
    ports:
      - 3000
  db:
    image: manuelarias/pets-db:1.2
    ports:
      - 5432:5432
    volumes:
      - pets-data:/var/lib/postgresql/data

volumes:
  pets-data: